---
require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - _snippets/*

# Layout/EndOfLine:
#   Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
  
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - specs/**/*
    - app/controllers/**/*
    - Rakefile

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - specs/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - db/migrations/**/*
    - Rakefile
